services:
  nginx:
    image: 'nginx:latest'
    restart: always
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d
      - ./log:/var/log/nginx
      - /etc/letsencrypt:/etc/letsencrypt
    environment:
      - TZ=Asia/Seoul